version: '3.3'
services:
  activityrankbotdev:
    container_name: activityRankBotDev
    restart: always
    build: .
    volumes:
      - ./src:/usr/src/app
      #- /usr/src/app/node_modules
    command: npm run development
